/// <reference types="vite/client" />

interface ImportMetaEnv {
  VITE_GOOGLE_MAPS_API_KEY?: string;
  VITE_GOOGLE_ANALYTICS_TRACKER_ID?: string;
  VITE_FIREBASE_API_KEY?: string;
  VITE_FIREBASE_AUTH_DOMAIN?: string;
  VITE_FIREBASE_DATABASE_URL?: string;
  VITE_FIREBASE_PROJECT_ID?: string;
  VITE_FIREBASE_STORAGE_BUCKET?: string;
  VITE_FIREBASE_MESSAGING_SENDER_ID?: string;
  VITE_FIREBASE_APP_ID?: string;
  VITE_FIREBASE_MEASUREMENT_ID?: string;
  VITE_OIDC_CLIENT_ID?: string;
  VITE_OIDC_SERVER_HOST?: string;
  VITE_OIDC_REDIRECT_URL?: string;
  VITE_OKTA_DOMAIN?: string;
  VITE_OKTA_CLIENT_ID?: string;
  VITE_OIDC_SCHEME?: string;
  VITE_SLACK_CLIENT_ID?: string;
  VITE_SLACK_APP_ID?: string;
  VITE_WEBEX_CLIENT_ID?: string;
  VITE_STRIPE_PUBLISHABLE_KEY?: string;
  VITE_STRIPE_PRO_MONTHLY_PRICE_ID?: string;
  VITE_STRIPE_PRO_YEARLY_PRICE_ID?: string;
  VITE_STRIPE_PREMIUM_MONTHLY_PRICE_ID?: string;
  VITE_STRIPE_PREMIUM_YEARLY_PRICE_ID?: string;
}
